### ISSUE TITLE
modelVersions[0] get undefined and crash nodeJs Server

### ISSUE THREAD

**Issue by Firoz01** [nicholascelestin/replicate-js#22]

**Comment by Firoz01** [comment]
I solved. It my mistake

**Comment by nicholascelestin** [comment]
Hey there, could you add some more detail to this issue, like a code snippet that isn't working?

**Comment by ericmillsio** [comment]
Error:
```
TypeError: Cannot read properties of undefined (reading '0')
    at ReplicateModel.getModelDetails (.../node_modules/replicate-js/replicate.js:70:35)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Function.fetch (.../node_modules/replicate-js/replicate.js:59:9)
    at test (...test.js:12:26)
    at Object.exports.handler (...test.js:76:16)
```

Believe they are mentioning this line: `const mostRecentVersion = modelVersions[0];`

**Comment by georgzoeller** [comment]
I get this as well, for some models consistently, for some models sporadically.

**Comment by tomryanx** [comment]
I was hitting this, and found that it was always happening when I had specified a model that didn't exist.
